trainer:
    num_epochs: 1
    learning_rate: 0.0001
    lr_warmup_steps: 500
    device: "cuda"


model:
    model_id: "stabilityai/stable-diffusion-2-1-base"
    num_inference_steps: 100

system:
    pf32_precision: 'high' # 'high' 'medium'
    random_state: 42     


data:
  processor_name: "/home/jovyan/.cache/huggingface/hub/models--stabilityai--stable-diffusion-2-1-base/snapshots/5ede9e4bf3e3fd1cb0ef2f7a3fff13ee514fdf06/tokenizer"
  dataloader:
    batch_size: 64
    num_workers: 40
    shuffle: True
  storage_options:
    anon: false
    key: 'officecds-user01'
    secret: 'jym0FuboUnR5VsPmCgYTGv1QQfglYZhPRWbEfS59'
    client_kwargs:
      endpoint_url: 'https://s3pd12.sbercloud.ru'
  dataset:
    shuffle_num: 12000
    image_size: 256
    seed: 6955
    data_file: /home/jovyan/vladimir/imagen/kandinsky4/data/train.list
  uncond_prob: 0.1